owner: pythoniaweb # GitHub username
repo: statusboom # GitHub repository name

sites:
  - name: Roblox site
    url: https://www.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Talant Roblox
    url: https://talent.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Thumbnail's Api
    url: https://thumbnails.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Asset's Delivery 
    url: https://assetdelivery.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Game Join Api
    url: http://gamejoin.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: 2FA Api
    url: https://twostepverification.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Account Settings
    url: https://accountsettings.roblox.com/
    maxResponseTime: 10000
    __dangerous__disable_verify_host: true
  - name: Voice Api
    url: https://voice.roblox.com/
  - name: Account Info
    url: https://accountinformation.roblox.com/
  - name: Auth Api
    url: https://auth.roblox.com/
  - name: Private Message Api
    url: https://privatemessages.roblox.com/
  - name: Chat Api
    url: https://chat.roblox.com/
  - name: Friends Api
    url: https://friends.roblox.com/
  - name: Billing Api
    url: https://billing.roblox.com/
  - name: Roblox Docs
    url: https://create.roblox.com/docs/reference/engine
  - name: Games Api
    url: https://games.roblox.com/
  - name: User's Api
    url: https://users.roblox.com/
  - name: Inventory Api
    url: https://inventory.roblox.com/
  - name: Data Storage Api
    url: https://gamepersistence.roblox.com/
  - name: Developer Api
    url: https://develop.roblox.com/
  - name: Groups Api
    url: https://groups.roblox.com/
  - name: Contact's Api
    url: https://contacts.roblox.com/
  - name: Catalog Api
    url: https://catalog.roblox.com/
  - name: Dev Forum
    url: https://devforum.roblox.com/
  - name: Avatar Api
    url: https://avatar.roblox.com/
  - name: Economy Api
    url: https://economy.roblox.com/
  - name: Premium Future's Api
    url: https://premiumfeatures.roblox.com/
  - name: Badge's Api
    url: https://badges.roblox.com/



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.boomhost.ml # Custom domain CNAME
  name: BoomHost Status # Status website titlename: upptime.js.org
  logoUrl: https://boomhost.ml/ico.ico
  favicon: https://boomhost.ml/ico.ico
  icon: https://boomhost.ml/ico.ico
  introTitle: "BoomHost Status Page."
  introMessage: Service Status of Hosting BoomHost.ml
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://boomhost.ml

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
