owner: pythoniaweb # GitHub username
repo: statusboom # GitHub repository name
sites: # List of endpoints to  track
  - name: Main
    url: http://boomhost.ml/index.php
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Client Area
    url: http://area.boomhost.ml/login.php
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Status Page
    url: http://status.boomhost.ml/index.html
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: BoomHost FTP
    url: http://myftp.boomhost.ml/index.html
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: cPanel
    url: https://cpanel.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: MySQL
    url: http://mysql.boomhost.ml/index.html
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: WHM Api
    url: http://cpanel.boomhost.ml
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Node 1
    url: http://nodea.boomhost.ml/index.html
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
  - name: Node 2
    url: http://nodeb.boomhost.ml/index.html
    maxResponseTime: 50000
    __dangerous__disable_verify_host: true
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.boomhost.ml # Custom domain CNAME
  name: BoomHost Status # Status website titlename: upptime.js.org
  logoUrl: https://boomhost.ml/ico.ico
  favicon: https://boomhost.ml/ico.ico
  icon: https://boomhost.ml/ico.ico
  introTitle: "BoomHost Status Page."
  introMessage: Service Status of Hosting BoomHost.ml
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://boomhost.ml

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
